config/routes.rb
Rails.application.routes.draw do
  root 'static#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'project_users/new', to: 'project_users#create'


  resources :users
  resources :projects
  resources :project_users


  
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project 
end

app/models/association.rb
class Association < ActiveRecord::Base
  belongs_to :user
  belongs_to :project 
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_users
  has_many :users, through: :project_users
end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :user_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :project_users
  has_many :projects, through: :project_users

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 6}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  private

   def require_login
     unless logged_in?
       flash[:error] = "You must be logged in to do that."
       redirect_to root_path
     end
   end
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  
  def index
    @project_user = ProjectUser.all
  end
  
  def show
    @project_user = ProjectUser.find(params[:id])
  end

  def new
  end

  def create
    @project_user = ProjectUser.new
    @user_id = params[:user_id]
    @project_id = params[:project_id]
    
    
    if @project_user.save
      flash[:notice] = "Congratulations. You've volunteered for a new project."
      redirect_to user_path(current_user)
    else
      flash[:error] = "Sorry, you've already volunteered for that project."
      redirect_to user_path(current_user)
    end
  end

  def edit
  end
  
  def update
    if @project_user.update
      flash[:notice] = "Your account profile has been updated."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def edit
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @project = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = "Your project has been created."
      redirect_to projects_path
    else
      flash.now[:error] = "There was a problem saving your project."
      render :new
    end
  end
  
  def update
  end

  def project_params
    params.require(:project).permit(:project_name, :project_description, :project_contact_person, :begin_date, :end_date)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.where(username: params[:username]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to projects_path
    else
      flash[:error] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash.now[:notice] = "You've successfully logged out."
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Congratulations. You've created a new account."
      redirect_to root_path
    else
      flash.now[:error] = "There's something wrong with your username or password."
      render :new
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account profile has been updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :phone_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Adopt-a-Cause", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
				<% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to projects_path do %> Available Projects<% end %></li>
							<li><%= link_to new_project_path do %> Create a New Project<% end %></li>
							<li><%= link_to user_path(current_user) do %> Your Projects <% end %></li>
							<li class="divider"></li>
              <li><%= link_to logout_path do %> Log Out <% end %></li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to new_user_path do %> Sign Up <% end %></li>
					<li><%= link_to login_path do %> Log In <% end %></li>
				<% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adopt-a-Cause</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-default">
          <div class="container">
            <%= render 'layouts/navigation' %>
	  </div>
        </div>
      </div>
    </header>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/project_users/index.html.erb
<%= link_to user_path(current_user) %>

app/views/projects/index.html.erb
<%= render 'shared/content_title', title: "Available Projects" %>

<div class="container-fluid" id="project-well">
  <% @project.each do |project| %>
    <ul class="project-list">
      <li class="well col-md-4 col-md-offset-1 text-center">
<%= project.project_name %> <br> <%= link_to 'Volunteer', new_project_user_path(:project_id => project.id, :user_id => current_user.id), :method => :post, :action => :create, class: "btn btn-primary" %> <%= link_to "More Info", project_path(project), class: "btn btn-warning" %>
      </li>
    </ul>
  <% end %>
</div>

app/views/projects/new.html.erb
<%= render 'shared/content_title', title: "Create a New Project" %>

<%= form_for @project do |f| %>
	<div class="container">
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-4 col-md-offset-2 control-label">			
					<%= f.label :project_name %>
					<%= f.text_field :project_name %>
				</div>
			</div>
		</div>
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-4 col-md-offset-2 control-label">
					<%= f.label :project_description %>
					<%= f.text_field :project_description %>
				</div>
			</div>
		</div>
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-4 col-md-offset-2 control-label">
					<%= f.label :project_contact_person %>
					<%= f.text_field :project_contact_person %>
				</div>
			</div>
		</div>
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-4 col-md-offset-2 control-label">
					<%= f.label :begin_date %>
					<%= f.text_field :begin_date %>
				</div>
			</div>
		</div>
		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-4 col-md-offset-2 control-label">
					<%= f.label :end_date %>
					<%= f.text_field :end_date %>
				</div>
			</div>
		</div>

		<div class="form-horizontal">
			<div class="form-group">
				<div class="col-md-2 col-md-offset-3 control-label">
					<%= f.submit class: "btn btn-primary" %>
				</div>
			</div>
		</div>
<% end %>
</form>
</div>

app/views/projects/show.html.erb
<%= render 'shared/content_title', title: "#{@project.project_name}" %>

<table class= "table table-hover responsive-table">
	<tr><td><strong>Description:</strong></td> <td><%= @project.project_description %></td></tr>
	<tr><td><strong>Contact:</strong></td> <td><%= mail_to "#{current_user.email}", @project.project_contact_person %></a></td></tr>
	<tr><td><strong>Begin Date:</strong></td> <td><%= @project.begin_date %></td></tr>
	<tr><td><strong>End Date:</strong></td> <td><%= @project.end_date %></td></tr>
</table>

app/views/shared/_content_title.html.erb
<div class="container">
  <div class="row">
    <div class="text-center">
      <h1><%= title %></h1>
      <hr>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="container">
    <div class="form-horizontal">
      <div class="form-group">
	<div class="col-md-4 col-md-offset-2 control-label">
	  <%= f.label :username %>
	  <%= f.text_field :username %>
	</div>
      </div>
    </div>
    <br>
    <div class="form-horizontal">
      <div class="form-group"> 
	<div class="col-md-4 col-md-offset-2 control-label">
	  <%= f.label :password %>
	  <%= f.password_field :password %>
	</div>
      </div>
    </div>
    <br>
    <div class="form-horizontal">
      <div class="form-group"> 
	<div class="col-md-4 col-md-offset-2 control-label">
	  <%= f.label :email %>
	  <%= f.text_field :email %>
	</div>
      </div>
    </div>
    <br>
    <div class="form-horizontal">
      <div class="form-group"> 
	<div class="col-md-4 col-md-offset-2 control-label">
	  <%= f.label :phone_number %>
	  (Optional) <%= f.text_field :phone_number %>
	</div>
      </div>
    </div>
    <br>
    <div class="form-horizontal">
      <div class="form-group"> 
	<div class="col-md-2 col-md-offset-3 control-label">
	  <%= f.submit class: "btn btn-primary" %>
	</div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Edit Profile" %>

<%= render 'form' %>

app/views/users/index.html.erb
<%= render 'shared/content_title', title: "Users" %>

<% @user.each do |user| %>
<ul>
  <li>  <%= link_to user.username, user_path(user.username) %></li>
</ul>
<% end %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Sign Up!" %>  

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "#{@user.username}'s Projects" %>

<div class="container well">
  <div class="row">

    <% if @user.projects.empty? %>
      <div class="col-md-8 col-md-offset-2">
	<span class="lead">You don't have any active projects. Would you like to <%= link_to projects_path do %> volunteer?</span><% end %>
      </div>
    <% else %>
      <div class="col-md-6 col-md-offset-1">
	<% @user.projects.each do |project| %>
	  <ul>
	    <li class="project-list"><%= link_to project.project_name, project_path(project) %> 
	  </ul>
	<% end %>
    <% end %>
    </div>
  </div>
</div>